'use strict'

// use like this (define an array with 2 entries for each set):
// const stress = stressed ? 0 : 1
// lexicalSets.DRESS[stress]
const LEXICALSETS_NORMAL = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['úr', 'ur'],
  FLEECE: ['íi', 'ii'],
  FACE: ['éi', 'ei'],
  PALM: ['áa', 'aa'],
  THOUGHT: ['óo', 'oo'],
  GOAT: ['óu', 'ou'],
  GOOSE: ['úu', 'uu'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áu', 'au'],
  CUTE: ['éu', 'eu'],
  NEAR: ['íir', 'iir'],
  SQUARE: ['éir', 'eir'],
  START: ['áar', 'aar'],
  NORTH: ['óor', 'oor'],
  POOR: ['úur', 'uur'],
  CURE: ['éur', 'eur'],
  FIRE: ['áir', 'air'],
  FLOUR: ['áur', 'aur'],
  COIR: ['óir', 'oir'],
  happY: 'i',
  lettER: 'ur',
  commA: 'e'
}

const LEXICALSETS_MACRON = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['úr', 'ur'],
  FLEECE: ['ī', 'ī'],
  FACE: ['ē', 'ē'],
  PALM: ['ā', 'ā'],
  THOUGHT: ['óo', 'oo'],
  GOAT: ['ō', 'ō'],
  GOOSE: ['ū', 'ū'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áu', 'au'],
  CUTE: ['éu', 'eu'],
  NEAR: ['īr', 'īr'],
  SQUARE: ['ēr', 'ēr'],
  START: ['ār', 'ār'],
  NORTH: ['ōr', 'ōr'],
  POOR: ['ūr', 'ūr'],
  CURE: ['éur', 'eur'],
  FIRE: ['áir', 'air'],
  FLOUR: ['áur', 'aur'],
  COIR: ['óir', 'oir'],
  happY: 'i',
  lettER: 'ur',
  commA: 'e'
}

const CONSONANTS_NORMAL = {
  B: 'b',
  CH: 'tc',
  D: 'd',
  DH: 'q',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'dj',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'ng',
  P: 'p',
  RR: 'r',
  S: 's',
  SH: 'c',
  T: 't',
  TH: 'x',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'j',
  Z: 'z',
  ZH: 'jh'
}

const CONSONANTS_MACRON = {
  B: 'b',
  CH: 'tc',
  D: 'd',
  DH: 'q',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'dʒ',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'ng',
  P: 'p',
  RR: 'r',
  S: 's',
  SH: 'c',
  T: 't',
  TH: 'x',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'j',
  Z: 'z',
  ZH: 'ʒ'
}
