export var LEXICALSETS = {}
export var CONSONANTS = {}

export function setSpelling (lexicalSets, consonants) {
  LEXICALSETS = lexicalSets
  CONSONANTS = consonants
}

// use like this (define an array with 2 entries for each set):
// const stress = stressed ? 0 : 1
// lexicalSets.DRESS[stress]
export const LEXICALSETS_EUROPEAN = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['ýr', 'yr'],
  FLEECE: ['íi', 'ii'],
  FACE: ['éi', 'ei'],
  PALM: ['áa', 'aa'],
  THOUGHT: ['óo', 'oo'],
  GOAT: ['óu', 'ou'],
  GOOSE: ['úu', 'uu'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áu', 'au'],
  CUTE: ['íu', 'iu'],
  NEAR: ['íir', 'iir'],
  SQUARE: ['éir', 'eir'],
  START: ['áar', 'aar'],
  NORTH: ['óor', 'oor'],
  POOR: ['úur', 'uur'],
  CURE: ['íur', 'iur'],
  FIRE: ['áir', 'air'],
  FLOUR: ['áur', 'aur'],
  COIR: ['óir', 'oir'],
  IAN: ['íe', 'ie'],
  happY: 'i',
  lettER: 'er',
  commA: 'e'
}

export const CONSONANTS_EUROPEAN = {
  B: 'b',
  CH: 'tc',
  D: 'd',
  DH: 'dh',
  EL: 'l',
  EM: 'm',
  EN: 'n',
  ER: 'r',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'dj',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'q',
  P: 'p',
  CRV: 'r',
  VRV: 'r',
  CS: 's',
  VS: 's',
  SH: 'c',
  T: 't',
  TH: 'th',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'y',
  ZC: 'z',
  ZV: 'z',
  ZH: 'j'
}

export const LEXICALSETS_MACRON = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['úr', 'ur'],
  FLEECE: ['ī', 'ī'],
  FACE: ['ē', 'ē'],
  PALM: ['ā', 'ā'],
  THOUGHT: ['óo', 'oo'],
  GOAT: ['ō', 'ō'],
  GOOSE: ['ū', 'ū'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áu', 'au'],
  CUTE: ['éu', 'eu'],
  NEAR: ['īr', 'īr'],
  SQUARE: ['ēr', 'ēr'],
  START: ['ār', 'ār'],
  NORTH: ['ōr', 'ōr'],
  POOR: ['ūr', 'ūr'],
  CURE: ['éur', 'eur'],
  FIRE: ['áir', 'air'],
  FLOUR: ['áur', 'aur'],
  COIR: ['óir', 'oir'],
  IAN: ['īe', 'īe'],
  happY: 'i',
  lettER: 'ur',
  commA: 'e'
}

export const CONSONANTS_MACRON = {
  B: 'b',
  CH: 'tc',
  D: 'd',
  DH: 'q',
  EL: 'l',
  EM: 'm',
  EN: 'n',
  ER: 'r',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'dʒ',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'ng',
  P: 'p',
  CRV: 'r',
  VRV: 'r',
  CS: 's',
  VS: 's',
  SH: 'c',
  T: 't',
  TH: 'x',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'j',
  ZC: 'z',
  ZV: 'z',
  ZH: 'ʒ'
}

export const LEXICALSETS_ASIAN = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['ýr', 'yr'],
  FLEECE: ['íe', 'ie'],
  FACE: ['éi', 'ei'],
  PALM: ['áa', 'aa'],
  THOUGHT: ['óo', 'oo'],
  GOAT: ['óu', 'ou'],
  GOOSE: ['úu', 'uu'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áo', 'ao'],
  CUTE: ['íu', 'iu'],
  NEAR: ['íir', 'iir'],
  SQUARE: ['éir', 'eir'],
  START: ['áar', 'aar'],
  NORTH: ['óor', 'oor'],
  POOR: ['úur', 'uur'],
  CURE: ['íur', 'iur'],
  FIRE: ['áir', 'air'],
  FLOUR: ['áur', 'aur'],
  COIR: ['óir', 'oir'],
  IAN: ['ía', 'ia'],
  happY: 'i',
  lettER: 'er',
  commA: 'e'
}

export const CONSONANTS_ASIAN = {
  B: 'b',
  CH: 'ch',
  D: 'd',
  DH: 'dh',
  EL: 'l',
  EM: 'm',
  EN: 'n',
  ER: 'r',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'j',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'ng',
  P: 'p',
  CRV: 'r',
  VRV: 'r',
  CS: 's',
  VS: 'ss',
  SH: 'sh',
  T: 't',
  TH: 'th',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'y',
  ZC: 's',
  ZV: 'x',
  ZH: 'z'
}

export const LEXICALSETS_ENGLISH = {
  KIT: ['í', 'i'],
  DRESS: ['é', 'e'],
  TRAP: ['á', 'a'],
  LOT: ['ó', 'o'],
  STRUT: ['ý', 'y'],
  FOOT: ['ú', 'u'],
  CLOTH: ['ó', 'o'],
  NURSE: ['ýr', 'yr'],
  FLEECE: ['íe', 'ie'],
  FACE: ['éi', 'ei'],
  PALM: ['áh', 'ah'],
  THOUGHT: ['áw', 'aw'],
  GOAT: ['óe', 'oe'],
  GOOSE: ['úw', 'uw'],
  PRICE: ['ái', 'ai'],
  CHOICE: ['ói', 'oi'],
  MOUTH: ['áo', 'ao'],
  CUTE: ['éu', 'eu'],
  NEAR: ['ír', 'ir'],
  SQUARE: ['ér', 'er'],
  START: ['ár', 'ar'],
  NORTH: ['ór', 'or'],
  POOR: ['úr', 'ur'],
  CURE: ['éur', 'eur'],
  FIRE: ['áier', 'aier'],
  FLOUR: ['áuer', 'auer'],
  COIR: ['óir', 'oir'],
  IAN: ['ía', 'ia'],
  happY: 'i',
  lettER: 'yr',
  commA: 'e'
}

export const CONSONANTS_ENGLISH = {
  B: 'b',
  CH: 'ch',
  D: 'd',
  DH: 'th',
  EL: 'l',
  EM: 'm',
  EN: 'en',
  ER: 'r',
  F: 'f',
  G: 'g',
  HH: 'h',
  J: 'j',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  NG: 'ng',
  P: 'p',
  CRV: 'r',
  VRV: 'rr',
  CS: 's',
  VS: 'ss',
  SH: 'sh',
  T: 't',
  TH: 'th',
  V: 'v',
  W: 'w',
  WH: 'wh',
  Y: 'y',
  ZC: 's',
  ZV: 'x',
  ZH: 'z'
}
