// Generated by ReScript, PLEASE EDIT WITH CARE


var lexicalSetsEuropean = {
  kit: [
    "í",
    "i"
  ],
  dress: [
    "é",
    "e"
  ],
  trap: [
    "á",
    "a"
  ],
  lot: [
    "ó",
    "o"
  ],
  strut: [
    "ý",
    "y"
  ],
  foot: [
    "ú",
    "u"
  ],
  cloth: [
    "ó",
    "o"
  ],
  nurse: [
    "ýr",
    "yr"
  ],
  fleece: [
    "íe",
    "ie"
  ],
  face: [
    "éi",
    "ei"
  ],
  palm: [
    "áa",
    "aa"
  ],
  thought: [
    "óa",
    "oa"
  ],
  goat: [
    "óu",
    "ou"
  ],
  goose: [
    "úu",
    "uu"
  ],
  price: [
    "ái",
    "ai"
  ],
  choice: [
    "ói",
    "oi"
  ],
  mouth: [
    "áu",
    "au"
  ],
  cute: [
    "iú",
    "iu"
  ],
  near: [
    "ír",
    "ir"
  ],
  square: [
    "éir",
    "eir"
  ],
  start: [
    "ár",
    "ar"
  ],
  north: [
    "ór",
    "or"
  ],
  force: [
    "ór",
    "or"
  ],
  poor: [
    "úr",
    "ur"
  ],
  cure: [
    "iúr",
    "iur"
  ],
  fire: [
    "áir",
    "air"
  ],
  flour: [
    "áur",
    "aur"
  ],
  coir: [
    "óir",
    "oir"
  ],
  ian: [
    "íe",
    "ie"
  ],
  happy: "i",
  letter: "er",
  comma: "e",
  seperator: "'"
};

var consonantsEuropean = {
  b: "b",
  ch: "tc",
  d: "d",
  dh: "dh",
  el: "el",
  em: "em",
  en: "en",
  er: "er",
  f: "f",
  g: "g",
  hh: "h",
  j: "dj",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "q",
  p: "p",
  crv: "r",
  vrv: "rr",
  cs: "s",
  vs: "ss",
  sh: "c",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "z",
  zh: "j"
};

var lexicalsetsMacron = {
  kit: [
    "í",
    "i"
  ],
  dress: [
    "é",
    "e"
  ],
  trap: [
    "á",
    "a"
  ],
  lot: [
    "ó",
    "o"
  ],
  strut: [
    "ý",
    "y"
  ],
  foot: [
    "ú",
    "u"
  ],
  cloth: [
    "ó",
    "o"
  ],
  nurse: [
    "úr",
    "ur"
  ],
  fleece: [
    "ī",
    "ī"
  ],
  face: [
    "ē",
    "ē"
  ],
  palm: [
    "ā",
    "ā"
  ],
  thought: [
    "óa",
    "oa"
  ],
  goat: [
    "ō",
    "ō"
  ],
  goose: [
    "ū",
    "ū"
  ],
  price: [
    "ái",
    "ai"
  ],
  choice: [
    "ói",
    "oi"
  ],
  mouth: [
    "áu",
    "au"
  ],
  cute: [
    "iú",
    "iu"
  ],
  near: [
    "īr",
    "īr"
  ],
  square: [
    "ēr",
    "ēr"
  ],
  start: [
    "ār",
    "ār"
  ],
  north: [
    "ōr",
    "ōr"
  ],
  force: [
    "ōr",
    "ōr"
  ],
  poor: [
    "ūr",
    "ūr"
  ],
  cure: [
    "iúr",
    "iur"
  ],
  fire: [
    "áir",
    "air"
  ],
  flour: [
    "áur",
    "aur"
  ],
  coir: [
    "óir",
    "oir"
  ],
  ian: [
    "īe",
    "īe"
  ],
  happy: "i",
  letter: "ur",
  comma: "e",
  seperator: "'"
};

var consonantsMacron = {
  b: "b",
  ch: "tc",
  d: "d",
  dh: "ð",
  el: "l",
  em: "m",
  en: "n",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "dʒ",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "r",
  cs: "s",
  vs: "s",
  sh: "c",
  t: "t",
  th: "þ",
  v: "v",
  w: "w",
  wh: "wh",
  y: "j",
  zc: "z",
  zv: "z",
  zh: "ʒ"
};

var lexicalsetsAsian = {
  kit: [
    "í",
    "i"
  ],
  dress: [
    "é",
    "e"
  ],
  trap: [
    "á",
    "a"
  ],
  lot: [
    "ó",
    "o"
  ],
  strut: [
    "ý",
    "y"
  ],
  foot: [
    "ú",
    "u"
  ],
  cloth: [
    "ó",
    "o"
  ],
  nurse: [
    "ýr",
    "yr"
  ],
  fleece: [
    "íe",
    "ie"
  ],
  face: [
    "éi",
    "ei"
  ],
  palm: [
    "áa",
    "aa"
  ],
  thought: [
    "óo",
    "oo"
  ],
  goat: [
    "óu",
    "ou"
  ],
  goose: [
    "úu",
    "uu"
  ],
  price: [
    "ái",
    "ai"
  ],
  choice: [
    "ói",
    "oi"
  ],
  mouth: [
    "áo",
    "ao"
  ],
  cute: [
    "iú",
    "iu"
  ],
  near: [
    "íir",
    "iir"
  ],
  square: [
    "éir",
    "eir"
  ],
  start: [
    "áar",
    "aar"
  ],
  north: [
    "óor",
    "oor"
  ],
  force: [
    "óor",
    "oor"
  ],
  poor: [
    "úur",
    "uur"
  ],
  cure: [
    "iúr",
    "iur"
  ],
  fire: [
    "áir",
    "air"
  ],
  flour: [
    "áur",
    "aur"
  ],
  coir: [
    "óir",
    "oir"
  ],
  ian: [
    "ía",
    "ia"
  ],
  happy: "i",
  letter: "er",
  comma: "e",
  seperator: "'"
};

var consonantsAsian = {
  b: "b",
  ch: "ch",
  d: "d",
  dh: "dh",
  el: "l",
  em: "m",
  en: "n",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "j",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "r",
  cs: "s",
  vs: "ss",
  sh: "sh",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "x",
  zh: "z"
};

var lexicalsetsEnglish = {
  kit: [
    "í",
    "i"
  ],
  dress: [
    "é",
    "e"
  ],
  trap: [
    "á",
    "a"
  ],
  lot: [
    "ó",
    "o"
  ],
  strut: [
    "ý",
    "y"
  ],
  foot: [
    "ú",
    "u"
  ],
  cloth: [
    "ó",
    "o"
  ],
  nurse: [
    "ýr",
    "yr"
  ],
  fleece: [
    "íe",
    "ie"
  ],
  face: [
    "éi",
    "ei"
  ],
  palm: [
    "áh",
    "ah"
  ],
  thought: [
    "áw",
    "aw"
  ],
  goat: [
    "óe",
    "oe"
  ],
  goose: [
    "úw",
    "uw"
  ],
  price: [
    "ái",
    "ai"
  ],
  choice: [
    "ói",
    "oi"
  ],
  mouth: [
    "áo",
    "ao"
  ],
  cute: [
    "éu",
    "eu"
  ],
  near: [
    "ír",
    "ir"
  ],
  square: [
    "ér",
    "er"
  ],
  start: [
    "ár",
    "ar"
  ],
  north: [
    "ór",
    "or"
  ],
  force: [
    "ór",
    "or"
  ],
  poor: [
    "úr",
    "ur"
  ],
  cure: [
    "éur",
    "eur"
  ],
  fire: [
    "áier",
    "aier"
  ],
  flour: [
    "áuer",
    "auer"
  ],
  coir: [
    "óir",
    "oir"
  ],
  ian: [
    "ía",
    "ia"
  ],
  happy: "i",
  letter: "yr",
  comma: "e",
  seperator: "'"
};

var consonantsEnglish = {
  b: "b",
  ch: "ch",
  d: "d",
  dh: "th",
  el: "l",
  em: "m",
  en: "en",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "j",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "rr",
  cs: "s",
  vs: "ss",
  sh: "sh",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "x",
  zh: "z"
};

var lexicalsetsGreek = {
  kit: [
    "ί",
    "ι"
  ],
  dress: [
    "έ",
    "ε"
  ],
  trap: [
    "ά",
    "α"
  ],
  lot: [
    "ό",
    "ο"
  ],
  strut: [
    "ώ",
    "ω"
  ],
  foot: [
    "ύ",
    "υ"
  ],
  cloth: [
    "ό",
    "ο"
  ],
  nurse: [
    "ώρ",
    "ωρ"
  ],
  fleece: [
    "ίι",
    "ιι"
  ],
  face: [
    "έι",
    "ει"
  ],
  palm: [
    "άα",
    "αα"
  ],
  thought: [
    "όα",
    "οα"
  ],
  goat: [
    "όυ",
    "ου"
  ],
  goose: [
    "ύυ",
    "υυ"
  ],
  price: [
    "άι",
    "αι"
  ],
  choice: [
    "όι",
    "οι"
  ],
  mouth: [
    "άυ",
    "αυ"
  ],
  cute: [
    "ιύ",
    "ιυ"
  ],
  near: [
    "ίρ",
    "ιρ"
  ],
  square: [
    "έρ",
    "ερ"
  ],
  start: [
    "άρ",
    "αρ"
  ],
  north: [
    "όρ",
    "ορ"
  ],
  force: [
    "όύρ",
    "ουρ"
  ],
  poor: [
    "ύρ",
    "υρ"
  ],
  cure: [
    "ιύρ",
    "ιυρ"
  ],
  fire: [
    "άιρ",
    "αιρ"
  ],
  flour: [
    "άυρ",
    "αυρ"
  ],
  coir: [
    "όιρ",
    "οιρ"
  ],
  ian: [
    "ία",
    "ια"
  ],
  happy: "ι",
  letter: "υρ",
  comma: "ε",
  seperator: "·"
};

var consonantsGreek = {
  b: "β",
  ch: "τξ",
  d: "δ",
  dh: "θ",
  el: "ελ",
  em: "εμ",
  en: "εν",
  er: "ερ",
  f: "φ",
  g: "γ",
  hh: "η",
  j: "δχ",
  k: "κ",
  l: "λ",
  m: "μ",
  n: "ν",
  ng: "νγ",
  p: "π",
  crv: "ρ",
  vrv: "ρρ",
  cs: "σ",
  vs: "σ",
  sh: "ξ",
  t: "τ",
  th: "θ",
  v: "ψ",
  w: "ϋ",
  wh: "ηϋ",
  y: "ϊ",
  zc: "ζ",
  zv: "ζ",
  zh: "χ"
};

var lexicalsetsRussian = {
  kit: [
    "и",
    "и"
  ],
  dress: [
    "е",
    "е"
  ],
  trap: [
    "а",
    "а"
  ],
  lot: [
    "о",
    "о"
  ],
  strut: [
    "э",
    "э"
  ],
  foot: [
    "у",
    "у"
  ],
  cloth: [
    "о",
    "о"
  ],
  nurse: [
    "эр",
    "эр"
  ],
  fleece: [
    "ии",
    "ии"
  ],
  face: [
    "еи",
    "еи"
  ],
  palm: [
    "аа",
    "аа"
  ],
  thought: [
    "оа",
    "оа"
  ],
  goat: [
    "оу",
    "оу"
  ],
  goose: [
    "уу",
    "уу"
  ],
  price: [
    "аи",
    "аи"
  ],
  choice: [
    "ои",
    "ои"
  ],
  mouth: [
    "ау",
    "ау"
  ],
  cute: [
    "ю",
    "ю"
  ],
  near: [
    "ир",
    "ир"
  ],
  square: [
    "ер",
    "ер"
  ],
  start: [
    "ар",
    "ар"
  ],
  north: [
    "ор",
    "ор"
  ],
  force: [
    "оур",
    "оур"
  ],
  poor: [
    "ур",
    "ур"
  ],
  cure: [
    "юр",
    "юр"
  ],
  fire: [
    "аир",
    "аир"
  ],
  flour: [
    "аур",
    "аур"
  ],
  coir: [
    "оир",
    "оир"
  ],
  ian: [
    "я",
    "я"
  ],
  happy: "и",
  letter: "р",
  comma: "е",
  seperator: "'"
};

var consonantsRussian = {
  b: "б",
  ch: "ч",
  d: "д",
  dh: "ц",
  el: "л",
  em: "м",
  en: "н",
  er: "р",
  f: "ф",
  g: "г",
  hh: "х",
  j: "ж",
  k: "к",
  l: "л",
  m: "м",
  n: "н",
  ng: "нг",
  p: "п",
  crv: "р",
  vrv: "рр",
  cs: "с",
  vs: "с",
  sh: "ш",
  t: "т",
  th: "ц",
  v: "в",
  w: "ы",
  wh: "ых",
  y: "й",
  zc: "з",
  zv: "з",
  zh: "щ"
};

var lexicalsetsIPA = {
  kit: [
    "'ɪ",
    "ɪ"
  ],
  dress: [
    "'ɛ",
    "ɛ"
  ],
  trap: [
    "'a",
    "a"
  ],
  lot: [
    "'ɑ",
    "ɑ"
  ],
  strut: [
    "'ɤ",
    "ɤ"
  ],
  foot: [
    "'ʊ",
    "ʊ"
  ],
  cloth: [
    "'ɔ",
    "ɔ"
  ],
  nurse: [
    "'ɚː",
    "ɚː"
  ],
  fleece: [
    "'iː",
    "iː"
  ],
  face: [
    "'eː",
    "eː"
  ],
  palm: [
    "'äː",
    "äː"
  ],
  thought: [
    "'ɔː",
    "ɔː"
  ],
  goat: [
    "'əʊ",
    "əʊ"
  ],
  goose: [
    "'uː",
    "uː"
  ],
  price: [
    "'aɪ",
    "aɪ"
  ],
  choice: [
    "'ɔɪ",
    "ɔɪ"
  ],
  mouth: [
    "'aʊ",
    "aʊ"
  ],
  cute: [
    "'ju",
    "ju"
  ],
  near: [
    "'iːr",
    "iːr"
  ],
  square: [
    "'eːr",
    "eːr"
  ],
  start: [
    "'aːr",
    "aːr"
  ],
  north: [
    "'ɔːr",
    "ɔːr"
  ],
  force: [
    "'oːr",
    "oːr"
  ],
  poor: [
    "'uːr",
    "uːr"
  ],
  cure: [
    "'jɚ",
    "jɚ"
  ],
  fire: [
    "'aɪr",
    "aɪr"
  ],
  flour: [
    "'aʊr",
    "aʊr"
  ],
  coir: [
    "'ɔɪr",
    "ɔɪr"
  ],
  ian: [
    "'iə",
    "iə"
  ],
  happy: "i",
  letter: "ɚ",
  comma: "ə",
  seperator: "'"
};

var consonantsIPA = {
  b: "b",
  ch: "ʧ",
  d: "d",
  dh: "ð",
  el: "l̩",
  em: "m̩",
  en: "n̩",
  er: "ɚ",
  f: "f",
  g: "g",
  hh: "h",
  j: "ʤ",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ŋ",
  p: "p",
  crv: "r",
  vrv: "r",
  cs: "s",
  vs: "s",
  sh: "ʃ",
  t: "t",
  th: "θ",
  v: "v",
  w: "w",
  wh: "w",
  y: "j",
  zc: "z",
  zv: "z",
  zh: "ʒ"
};

export {
  lexicalSetsEuropean ,
  consonantsEuropean ,
  lexicalsetsMacron ,
  consonantsMacron ,
  lexicalsetsAsian ,
  consonantsAsian ,
  lexicalsetsEnglish ,
  consonantsEnglish ,
  lexicalsetsGreek ,
  consonantsGreek ,
  lexicalsetsRussian ,
  consonantsRussian ,
  lexicalsetsIPA ,
  consonantsIPA ,
}
/* No side effect */
