// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var lexicalSets = {
  contents: undefined
};

var consonants = {
  contents: undefined
};

function setSpelling(lexicalSets_, consonants_) {
  lexicalSets.contents = lexicalSets_;
  consonants.contents = consonants_;
  
}

var lexicalSetsEuropean = {
  kit: [
    "\xc3\xad",
    "i"
  ],
  dress: [
    "\xc3\xa9",
    "e"
  ],
  trap: [
    "\xc3\xa1",
    "a"
  ],
  lot: [
    "\xc3\xb3",
    "o"
  ],
  strut: [
    "\xc3\xbd",
    "y"
  ],
  foot: [
    "\xc3\xba",
    "u"
  ],
  cloth: [
    "\xc3\xb3",
    "o"
  ],
  nurse: [
    "\xc3\xbdr",
    "yr"
  ],
  fleece: [
    "\xc3\xade",
    "ie"
  ],
  face: [
    "\xc3\xa9i",
    "ei"
  ],
  palm: [
    "\xc3\xa1a",
    "aa"
  ],
  thought: [
    "\xc3\xb3a",
    "oa"
  ],
  goat: [
    "\xc3\xb3u",
    "ou"
  ],
  goose: [
    "\xc3\xbau",
    "uu"
  ],
  price: [
    "\xc3\xa1i",
    "ai"
  ],
  choice: [
    "\xc3\xb3i",
    "oi"
  ],
  mouth: [
    "\xc3\xa1u",
    "au"
  ],
  cute: [
    "\xc3\xadu",
    "iu"
  ],
  near: [
    "\xc3\xadr",
    "ir"
  ],
  square: [
    "\xc3\xa9ir",
    "eir"
  ],
  start: [
    "\xc3\xa1r",
    "ar"
  ],
  north: [
    "\xc3\xb3r",
    "or"
  ],
  poor: [
    "\xc3\xbar",
    "ur"
  ],
  cure: [
    "\xc3\xadur",
    "iur"
  ],
  fire: [
    "\xc3\xa1ir",
    "air"
  ],
  flour: [
    "\xc3\xa1ur",
    "aur"
  ],
  coir: [
    "\xc3\xb3ir",
    "oir"
  ],
  ian: [
    "\xc3\xade",
    "ie"
  ],
  happy: "i",
  letter: "er",
  comma: "e"
};

var consonantsEuropean = {
  b: "b",
  ch: "tc",
  d: "d",
  dh: "dh",
  el: "el",
  em: "em",
  en: "en",
  er: "er",
  f: "f",
  g: "g",
  hh: "h",
  j: "dj",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "q",
  p: "p",
  crv: "r",
  vrv: "rr",
  cs: "s",
  vs: "ss",
  sh: "c",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "z",
  zh: "j"
};

var lexicalsetsMacron = {
  kit: [
    "\xc3\xad",
    "i"
  ],
  dress: [
    "\xc3\xa9",
    "e"
  ],
  trap: [
    "\xc3\xa1",
    "a"
  ],
  lot: [
    "\xc3\xb3",
    "o"
  ],
  strut: [
    "\xc3\xbd",
    "y"
  ],
  foot: [
    "\xc3\xba",
    "u"
  ],
  cloth: [
    "\xc3\xb3",
    "o"
  ],
  nurse: [
    "\xc3\xbar",
    "ur"
  ],
  fleece: [
    "\xc4\xab",
    "\xc4\xab"
  ],
  face: [
    "\xc4\x93",
    "\xc4\x93"
  ],
  palm: [
    "\xc4\x81",
    "\xc4\x81"
  ],
  thought: [
    "\xc3\xb3a",
    "oa"
  ],
  goat: [
    "\xc5\x8d",
    "\xc5\x8d"
  ],
  goose: [
    "\xc5\xab",
    "\xc5\xab"
  ],
  price: [
    "\xc3\xa1i",
    "ai"
  ],
  choice: [
    "\xc3\xb3i",
    "oi"
  ],
  mouth: [
    "\xc3\xa1u",
    "au"
  ],
  cute: [
    "\xc3\xadu",
    "iu"
  ],
  near: [
    "\xc4\xabr",
    "\xc4\xabr"
  ],
  square: [
    "\xc4\x93r",
    "\xc4\x93r"
  ],
  start: [
    "\xc4\x81r",
    "\xc4\x81r"
  ],
  north: [
    "\xc5\x8dr",
    "\xc5\x8dr"
  ],
  poor: [
    "\xc5\xabr",
    "\xc5\xabr"
  ],
  cure: [
    "\xc3\xadur",
    "iur"
  ],
  fire: [
    "\xc3\xa1ir",
    "air"
  ],
  flour: [
    "\xc3\xa1ur",
    "aur"
  ],
  coir: [
    "\xc3\xb3ir",
    "oir"
  ],
  ian: [
    "\xc4\xabe",
    "\xc4\xabe"
  ],
  happy: "i",
  letter: "ur",
  comma: "e"
};

var consonantsMacron = {
  b: "b",
  ch: "tc",
  d: "d",
  dh: "\xc3\xb0",
  el: "l",
  em: "m",
  en: "n",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "d\xca\x92",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "r",
  cs: "s",
  vs: "s",
  sh: "c",
  t: "t",
  th: "\xc3\xbe",
  v: "v",
  w: "w",
  wh: "wh",
  y: "j",
  zc: "z",
  zv: "z",
  zh: "\xca\x92"
};

var lexicalsetsAsian = {
  kit: [
    "\xc3\xad",
    "i"
  ],
  dress: [
    "\xc3\xa9",
    "e"
  ],
  trap: [
    "\xc3\xa1",
    "a"
  ],
  lot: [
    "\xc3\xb3",
    "o"
  ],
  strut: [
    "\xc3\xbd",
    "y"
  ],
  foot: [
    "\xc3\xba",
    "u"
  ],
  cloth: [
    "\xc3\xb3",
    "o"
  ],
  nurse: [
    "\xc3\xbdr",
    "yr"
  ],
  fleece: [
    "\xc3\xade",
    "ie"
  ],
  face: [
    "\xc3\xa9i",
    "ei"
  ],
  palm: [
    "\xc3\xa1a",
    "aa"
  ],
  thought: [
    "\xc3\xb3o",
    "oo"
  ],
  goat: [
    "\xc3\xb3u",
    "ou"
  ],
  goose: [
    "\xc3\xbau",
    "uu"
  ],
  price: [
    "\xc3\xa1i",
    "ai"
  ],
  choice: [
    "\xc3\xb3i",
    "oi"
  ],
  mouth: [
    "\xc3\xa1o",
    "ao"
  ],
  cute: [
    "\xc3\xadu",
    "iu"
  ],
  near: [
    "\xc3\xadir",
    "iir"
  ],
  square: [
    "\xc3\xa9ir",
    "eir"
  ],
  start: [
    "\xc3\xa1ar",
    "aar"
  ],
  north: [
    "\xc3\xb3or",
    "oor"
  ],
  poor: [
    "\xc3\xbaur",
    "uur"
  ],
  cure: [
    "\xc3\xadur",
    "iur"
  ],
  fire: [
    "\xc3\xa1ir",
    "air"
  ],
  flour: [
    "\xc3\xa1ur",
    "aur"
  ],
  coir: [
    "\xc3\xb3ir",
    "oir"
  ],
  ian: [
    "\xc3\xada",
    "ia"
  ],
  happy: "i",
  letter: "er",
  comma: "e"
};

var consonantsAsian = {
  b: "b",
  ch: "ch",
  d: "d",
  dh: "dh",
  el: "l",
  em: "m",
  en: "n",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "j",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "r",
  cs: "s",
  vs: "ss",
  sh: "sh",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "x",
  zh: "z"
};

var lexicalsetsEnglish = {
  kit: [
    "\xc3\xad",
    "i"
  ],
  dress: [
    "\xc3\xa9",
    "e"
  ],
  trap: [
    "\xc3\xa1",
    "a"
  ],
  lot: [
    "\xc3\xb3",
    "o"
  ],
  strut: [
    "\xc3\xbd",
    "y"
  ],
  foot: [
    "\xc3\xba",
    "u"
  ],
  cloth: [
    "\xc3\xb3",
    "o"
  ],
  nurse: [
    "\xc3\xbdr",
    "yr"
  ],
  fleece: [
    "\xc3\xade",
    "ie"
  ],
  face: [
    "\xc3\xa9i",
    "ei"
  ],
  palm: [
    "\xc3\xa1h",
    "ah"
  ],
  thought: [
    "\xc3\xa1w",
    "aw"
  ],
  goat: [
    "\xc3\xb3e",
    "oe"
  ],
  goose: [
    "\xc3\xbaw",
    "uw"
  ],
  price: [
    "\xc3\xa1i",
    "ai"
  ],
  choice: [
    "\xc3\xb3i",
    "oi"
  ],
  mouth: [
    "\xc3\xa1o",
    "ao"
  ],
  cute: [
    "\xc3\xa9u",
    "eu"
  ],
  near: [
    "\xc3\xadr",
    "ir"
  ],
  square: [
    "\xc3\xa9r",
    "er"
  ],
  start: [
    "\xc3\xa1r",
    "ar"
  ],
  north: [
    "\xc3\xb3r",
    "or"
  ],
  poor: [
    "\xc3\xbar",
    "ur"
  ],
  cure: [
    "\xc3\xa9ur",
    "eur"
  ],
  fire: [
    "\xc3\xa1ier",
    "aier"
  ],
  flour: [
    "\xc3\xa1uer",
    "auer"
  ],
  coir: [
    "\xc3\xb3ir",
    "oir"
  ],
  ian: [
    "\xc3\xada",
    "ia"
  ],
  happy: "i",
  letter: "yr",
  comma: "e"
};

var consonantsEnglish = {
  b: "b",
  ch: "ch",
  d: "d",
  dh: "th",
  el: "l",
  em: "m",
  en: "en",
  er: "r",
  f: "f",
  g: "g",
  hh: "h",
  j: "j",
  k: "k",
  l: "l",
  m: "m",
  n: "n",
  ng: "ng",
  p: "p",
  crv: "r",
  vrv: "rr",
  cs: "s",
  vs: "ss",
  sh: "sh",
  t: "t",
  th: "th",
  v: "v",
  w: "w",
  wh: "wh",
  y: "y",
  zc: "s",
  zv: "x",
  zh: "z"
};

export {
  lexicalSets ,
  consonants ,
  setSpelling ,
  lexicalSetsEuropean ,
  consonantsEuropean ,
  lexicalsetsMacron ,
  consonantsMacron ,
  lexicalsetsAsian ,
  consonantsAsian ,
  lexicalsetsEnglish ,
  consonantsEnglish ,
  
}
/* No side effect */
